from django.conf.urls.defaults import *

urlpatterns = patterns('contacts.views',
	url(r'^companies/page/(?P<page>\d+)/$',
		view = 'company_list',
		name = 'contacts_company_list_paginated',
	),
	url(r'^companies/add/$',
		view = 'company_create',
		name = 'contants_company_create',
	),
	url(r'^companies/(?P<slug>[-\w]+)/delete/$',
		view = 'company_delete',
		name = 'contacts_company_delete'
	),
	url(r'^companies/(?P<slug>[-\w]+)/edit/$',
		view = 'company_update',
		name = 'contacts_company_update'
	),
	url(r'^companies/(?P<slug>[-\w]+)/$',
		view = 'company_detail',
		name = 'contacts_company_detail'
	),
	url(r'^companies/$',
		view = 'company_list',
		name = 'contacts_company_list',
	),
	url(r'^people/page/(?P<page>\d+)/$',
		view = 'person_list',
		name = 'contacts_person_list_paginated',
	),
	url(r'^people/add/$',
		view = 'person_create',
		name = 'contants_person_create',
	),
	url(r'^people/(?P<slug>[-\w]+)/delete/$',
		view = 'person_delete',
		name = 'contacts_person_delete'
	),
	url(r'^people/(?P<slug>[-\w]+)/edit/$',
		view = 'person_update',
		name = 'contacts_person_update'
	),
	url(r'^people/(?P<slug>[-\w]+)/$',
		view = 'person_detail',
		name = 'contacts_person_detail',
	),
	url(r'^people/$',
		view = 'person_list',
		name = 'contacts_person_list',
	),
)